"""initial

Revision ID: 5fbca53e8bfd
Revises: 
Create Date: 2025-01-15 10:24:15.855546

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5fbca53e8bfd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "WIN", "FAILED", name="bet_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.CheckConstraint("amount > 0", name="check_amount_positive"),
        sa.PrimaryKeyConstraint("id", name="bet_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    # ### end Alembic commands ###
